language: go

branches:
  only:
  - deploy

services:
  - docker

addons:
  hosts:
    - node-1
    - node-2
    - node-3
    - node-4
    - node-5
    - node-6

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - make docker
  - ./scripts/smoke_test.sh

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make push
