language: go

branches:
  only:
  - master
  - develop

services:
  - docker

addons:
  hosts:
    - node-1
    - node-2
    - node-3
    - node-4
    - node-5
    - node-6

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - make docker_image && ./test/integration/test.sh

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push_image ;
    elif [[ "$TRAVIS_BRANCH" == "develop" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push_dev_image  ;
    fi
